# NumPy

## 1D and 2D Arrays

In [68]:
import numpy as np

a = np.array([1, 2, 3])

print(a)

print(a.shape)

[1 2 3]
(3,)


In [69]:
import numpy as np

a = np.array([1, 1, 2, 3])

print(a.shape)

(4,)


In [70]:
"""

A Table:
[1,2,3]
[4,5,6]

"""

"""
list of lists
[[1,2,3],
 [4,5,6]]

"""

'\nlist of lists\n[[1,2,3],\n [4,5,6]]\n\n'

In [71]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])

print(b)

print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [72]:
import numpy as np

c = np.array([[1.1, 2, 3], [4, 5.1, 6]])

print(c)

[[1.1 2.  3. ]
 [4.  5.1 6. ]]


In [73]:
import numpy as np

c = np.array([[1.1, 2, 3], [True, 5.1, "6"]])

print(c)

[['1.1' '2' '3']
 ['True' '5.1' '6']]


## NumPy Reshape

In [74]:
b.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
b.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [76]:
# This line of code gives us error
# b.reshape((5,))

## Functions for Generating NumPy Arrays

In [77]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [80]:
np.arange(1, 10)
# Like numpy range function it goes up until the stopping value -1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
np.arange(1, 10, 2)
# 2 means it goes up by twos
# Start at 1, go up by two, until it hits 10 - 1

array([1, 3, 5, 7, 9])

In [82]:
np.linspace(1, 11, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [83]:
np.linspace(1, 12, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ])

## Indexing

In [84]:
b[0]

array([1, 2, 3])

In [85]:
b[1]

array([4, 5, 6])

In [86]:
# This line gives us error
# b[2]

In [87]:
# Just like python indexing The ':' operators means you want everything
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
b[:, 0]

array([1, 4])

In [89]:
b[0, 0]

np.int64(1)

## Parallelization 

In [90]:
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [91]:
for i in range(2):
    for j in range(3):
        b[i, j] = b[i, j] * 2

b

# ! We should not do this
# It rewrote b but the first one didn't do this
# First one made a copy cut the second actually rewrote b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [92]:
b > 7

array([[False, False, False],
       [ True,  True,  True]])

In [93]:
b[b > 7]

array([ 8, 10, 12])