# NumPy

## 1D and 2D Arrays

In [2]:
import numpy as np

a = np.array([1, 2, 3])

print(a)

print(a.shape)

[1 2 3]
(3,)


In [3]:
import numpy as np

a = np.array([1, 1, 2, 3])

print(a.shape)

(4,)


In [4]:
"""

A Table:
[1,2,3]
[4,5,6]

"""

"""
list of lists
[[1,2,3],
 [4,5,6]]

"""

'\nlist of lists\n[[1,2,3],\n [4,5,6]]\n\n'

In [5]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])

print(b)

print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
import numpy as np

c = np.array([[1.1, 2, 3], [4, 5.1, 6]])

print(c)

[[1.1 2.  3. ]
 [4.  5.1 6. ]]


In [7]:
import numpy as np

c = np.array([[1.1, 2, 3], [True, 5.1, "6"]])

print(c)

[['1.1' '2' '3']
 ['True' '5.1' '6']]


## NumPy Reshape

In [8]:
b.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
b.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [10]:
# This line of code gives us error
# b.reshape((5,))

## Functions for Generating NumPy Arrays

In [11]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
np.arange(1, 10)
# Like numpy range function it goes up until the stopping value -1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1, 10, 2)
# 2 means it goes up by twos
# Start at 1, go up by two, until it hits 10 - 1

array([1, 3, 5, 7, 9])

In [16]:
np.linspace(1, 11, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [17]:
np.linspace(1, 12, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ])

## Indexing

In [18]:
b[0]

array([1, 2, 3])

In [19]:
b[1]

array([4, 5, 6])

In [20]:
# This line gives us error
# b[2]

In [21]:
# Just like python indexing The ':' operators means you want everything
b[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
b[:, 0]

array([1, 4])

In [23]:
b[0, 0]

np.int64(1)

## Parallelization 

In [24]:
b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
for i in range(2):
    for j in range(3):
        b[i, j] = b[i, j] * 2

b

# ! We should not do this
# It rewrote b but the first one didn't do this
# First one made a copy cut the second actually rewrote b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
b > 7

array([[False, False, False],
       [ True,  True,  True]])

In [27]:
b[b > 7]

array([ 8, 10, 12])

In [28]:
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [29]:
np.mean(b)

np.float64(7.0)

In [ ]:
# avg of each row
np.mean(b, axis=1)

array([ 4., 10.])

In [ ]:
# avg of each column
np.mean(b, axis=0)

array([5., 7., 9.])

In [ ]:
# There is one axis for every single dimension
# This line gives us an error
# np.mean(b, axis=2)

In [33]:
np.mean(b, axis=-1)

array([ 4., 10.])

In [34]:
# Calculating Standard Deviation
np.std(b, axis=-1)

array([1.63299316, 1.63299316])

In [35]:
# Stack NumPy arrays and join them together
# By default axis is zero
np.concatenate([b, b * 2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 4,  8, 12],
       [16, 20, 24]])

In [36]:
np.concatenate([b, b * 2], axis=1)

array([[ 2,  4,  6,  4,  8, 12],
       [ 8, 10, 12, 16, 20, 24]])

## Attention !!! How NumPy arrays arise in practice?

In [2]:
from tensorflow.keras.datasets import mnist

# Turn mnist to NumPy arrays
(X_train, y_train), (X_test, y_test) = mnist.load_data()