# NumPy

## 1D and 2D Arrays

In [5]:
import numpy as np

a = np.array([1, 2, 3])

print(a)

print(a.shape)

[1 2 3]
(3,)


In [13]:
import numpy as np

a = np.array([1, 1, 2, 3])

print(a.shape)

(4,)


In [7]:
"""

A Table:
[1,2,3]
[4,5,6]

"""

"""
list of lists
[[1,2,3],
 [4,5,6]]

"""

'\nlist of lists\n[[1,2,3],\n [4,5,6]]\n\n'

In [8]:
import numpy as np

b = np.array([[1, 2, 3], [4, 5, 6]])

print(b)

print(b.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [9]:
import numpy as np

c = np.array([[1.1, 2, 3], [4, 5.1, 6]])

print(c)

[[1.1 2.  3. ]
 [4.  5.1 6. ]]


In [10]:
import numpy as np

c = np.array([[1.1, 2, 3], [True, 5.1, "6"]])

print(c)

[['1.1' '2' '3']
 ['True' '5.1' '6']]


## NumPy Reshape

In [11]:
b.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
b.reshape((6,))

array([1, 2, 3, 4, 5, 6])

In [17]:
b.reshape((5,))

ValueError: cannot reshape array of size 6 into shape (5,)

## Functions for Generating NumPy Arrays

In [19]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((2, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [25]:
np.arange(1, 10)
# Like numpy range function it goes up until the stopping value -1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(1, 10, 2)
# 2 means it goes up by twos
# Start at 1, go up by two, until it hits 10 - 1

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1, 11, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [32]:
np.linspace(1, 12, num=11)
# np.arange is just for int but linspace works well with floating point values
# what steps it needed to evenly space 11 numbers between 1 and eleven

array([ 1. ,  2.1,  3.2,  4.3,  5.4,  6.5,  7.6,  8.7,  9.8, 10.9, 12. ])