# NumPy

## 1D and 2D Arrays

In [5]:
import numpy as np

arr = np.array([1, 2, 3])

print(arr)

[1 2 3]


In [7]:
print(arr.shape)

(3,)


In [8]:
import numpy as np

arr = np.array([1, 1, 2, 3])

print(arr.shape)

(4,)


In [ ]:
"""

A Table:
[1,2,3]
[4,5,6]

"""

"""
list of lists
[[1,2,3],
 [4,5,6]]

"""

'\n[[1,2,3],\n[4,5,6]]\n'

In [2]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
